const SOURCES = {
  REFERRAL: 'REFERRAL',
  INTERNAL: 'INTERNAL',
  JOB_BOARD: 'JOB_BOARD',
  OTHER: 'OTHER'
};

const APPLICATION_STATUS = {
  RECEIVED: 'RECEIVED',
  IN_REVIEW: 'IN_REVIEW',
  REJECTED: 'REJECTED',
  HIRED: 'HIRED'
};

const VACANCY_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED'
};

const PRIORITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  TOP: 'TOP'
};

module.exports = {
  SOURCES,
  APPLICATION_STATUS,
  VACANCY_STATUS,
  PRIORITIES
};